language: ruby
sudo: required
rvm: 2.4
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
after_success:
  - bundle exec rake wax:ghbranch
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
