language: ruby
sudo: required
rvm: 2.4
addons:
  chrome: stable
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
after_success:
  - bundle exec rake wax:push:s3
  - bundle exec rake wax:push:gh
deploy:
  provider: s3
  access_key_id: $AWS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "cul-s3-dlst-travis-demo"
  skip_cleanup: true
