# basic settings
title: The Biggert Collection of Architectural Vignettes
description: The Biggert Collection of Architectural Vignettes on Commercial Stationery
url: ''
baseurl: '/biggert'
gh-baseurl: '/ldpd-biggert'

# build settings
markdown: kramdown
exclude: [Gemfile*, vendor, Rakefile, README.md, spec, package.json]
permalink: pretty

# wax collection settings
collections:
  pages:
    output: true
  items:
    source: biggert.json
    layout: iiif-image-page
    output: true
    lunr_index:
      fields:
        - date_other
        - sort_title
        - title
        - subject_hierarchical_geographic
        - subject_name
        - genre
        - coordinates
        - call_number
        - doi
        - thumbnail # for map markers
menu:
  - label: About
    link: '/about-the-collection/'
    sub:
      - label: About the Collection
        link: '/about-the-collection/'
      - label: Rights & Permissions
        link: '/rights/'
  - label: Browse the Map
    link: '/locations/'
  - label: Search
    link: '/search/'

quoll:
  full:
    page: search
    terms:
      - 'check'
      - 'new york'
      - 'avery'
      - 'michigan'

js:
  leaflet:
    version: 1.3.1
    cdn: https://unpkg.com/leaflet@1.3.1/dist/leaflet.js
  leaflet-iiif:
    version: 2.0.1
    cdn: https://cdn.jsdelivr.net/npm/leaflet-iiif@2.0.1/leaflet-iiif.min.js
  jquery:
    version: 3.2.1
    cdn: https://code.jquery.com/jquery-3.2.1.min.js
  jquery-migrate:
    version: 3.0.0
    cdn: https://code.jquery.com/jquery-migrate-3.0.0.min.js
  elasticlunr:
    version: 0.9.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  leaflet-markercluster:
    version: 1.3.0
    cdn: https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js


# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
