- label: Title
  field: title
- label: Genre
  field: genre
- label: Form
  field: form
- label: Call Number
  field: call_number
- label: Date
  field: date_other_textual
- label: DOI
  field: doi
- label: Companies
  field: subject_name
